name: Update GitHub Profile

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual execution

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate Experience and Update README
        run: |
          START_YEAR=2019
          CURRENT_YEAR=$(date +'%Y')
          EXPERIENCE=$((CURRENT_YEAR - START_YEAR))
          
          sed -i "s/[0-9]\+ years of experience/${EXPERIENCE} years of experience/g" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "Updated years of experience"
          git push
